src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Repository\AdRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $dateUpdate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Dog::class, mappedBy="ad", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $dogs;

    /**
     * @ORM\ManyToOne(targetEntity=Marketer::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Marketer $marketer;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isProvide = false;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="ad")
     */
    private $pictures;

    public function __construct()
    {
        $this->dogs = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getPicturesAllDogs(): Collection
    {
        $pictures = new ArrayCollection();
        $dogs = $this->getDogs();
        foreach ($dogs as $dog) {
            foreach ($dog->getPictures() as $picture) {
                $pictures->add($picture->getUrl());
            }
        }

        return $pictures;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->dateUpdate;
    }

    public function setDateUpdate(\DateTimeInterface $dateUpdate): self
    {
        $this->dateUpdate = $dateUpdate;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Dog[]
     */
    public function getDogs(): Collection
    {
        return $this->dogs;
    }

    public function addDog(Dog $dog): self
    {
        if (!$this->dogs->contains($dog)) {
            $this->dogs[] = $dog;
            $dog->setAd($this);
        }

        return $this;
    }

    public function removeDog(Dog $dog): self
    {
        if ($this->dogs->removeElement($dog)) {
            // set the owning side to null (unless already changed)
            if ($dog->getAd() === $this) {
                $dog->setAd(null);
            }
        }

        return $this;
    }

    public function getMarketer(): ?Marketer
    {
        return $this->marketer;
    }

    public function setMarketer(?Marketer $marketer): self
    {
        $this->marketer = $marketer;

        return $this;
    }

    public function getIsProvide(): ?bool
    {
        return $this->isProvide;
    }

    public function setIsProvide(?bool $isProvide): self
    {
        $this->isProvide = $isProvide;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setAd($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getAd() === $this) {
                $picture->setAd(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Entity\Dog;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', \Symfony\Component\Form\Extension\Core\Type\TextType::class, [
                'label' => 'Titre',
            ])
            ->add('description', \Symfony\Component\Form\Extension\Core\Type\TextType::class, [
                'label' => 'Description',
            ])
            ->add('dogs', EntityType::class, [
                'label' => 'Chiens de l\'annonce ',
                'class' => Dog::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('d')
                        ->where('d.ad is null and d.isAvailable = true')
                        ->orderBy('d.name');
                },
                //  'choice_label' => 'name',  // commenté car un toString sur Race le remplace
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Marketer;
use App\Form\AdType;
use App\Repository\AdRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdController extends AbstractController
{
    /**
     @Route("/ad", name="ad")
     */
    public function index(Request $request, EntityManagerInterface $em): Response
    {
        $ad = new Ad();
        $form = $this->createForm(AdType::class, $ad, [
            'method' => 'POST',
        ]);

        /** @var Marketer $marketer */
        $marketer = $this->getUser();
        $ad->setMarketer($marketer);

        $currentDate = new DateTime();
        $ad->setDateUpdate($currentDate);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($ad);
            $em->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('ad/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/ad/show/{id}", name="ad_show", requirements={"id"="\d+"})
     */
    public function details(AdRepository $adRepository, int $id): Response
    {
        $ad = $adRepository->find($id);
        $dogs = $ad->getDogs();

        return $this->render('ad/detail.hmtl.twig', [
            'ad' => $ad,
            'dogs' => $dogs,
        ]);
    }
}

src/Controller/AdsController.php
<?php

namespace App\Controller;

use App\Repository\AdRepository;
use Knp\Component\Pager\PaginatorInterface;
use Proxies\__CG__\App\Entity\Ad;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdsController extends AbstractController
{
    private AdRepository  $adRepository;

    /**
     * @Route("/ads", name="ads")
     */
    public function index(Request $request, AdRepository $adRepository, PaginatorInterface $paginator): Response
    {
        //       $this->adRepository = $adRepository;

        //       $ads = $adRepository->findAll();
        $donnees = $this->getDoctrine()->getRepository(Ad::class)->findBy([], []);
        $ads = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            6 // Nombre de résultats par page
        );

        return $this->render('ads/index.html.twig', [
            'controller_name' => 'AdsController',
            'ads' => $ads,
        ]);
    }
}

templates/ad/detail.hmtl.twig
{% extends 'base.html.twig' %}

{% block title %}Detail annonce{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        <div class="card col-8">
            {#    START Caroussel #}
            <div id="carouselExampleControls" class="carousel slide card-img-top" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ ad.picturesAllDogs.first }}" class="d-block w-100 img-carousel" alt="...">
                    </div>
                    {% for picture in ad.picturesAllDogs %}
                        {% if picture == ad.picturesAllDogs.first %}
                        {% else %}
                        <div class="carousel-item">
                            <img src="{{ picture }}" class="d-block w-100 img-carousel" alt="...">
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
            {#    END Caroussel #}
            <div class="card-body">
                <div class="d-flex card-title justify-content-between">
                    <h5>{{ ad.title }}</h5> <p>{{ ad.dateUpdate.timestamp |date("Y-m-d")}}</p>
                </div>
                <h6 class="card-title"></h6>
                <ul class="list-group">
                    <li class="list-group-item">Chiens :</li>
                    {% for dog in dogs %}
                        <li class="list-group-item">Nom : {{ dog.name }} Race : {{ dog.races.first }} {% if dog.lof %} Le chien est LOF{% endif %}</li>
                    {% endfor %}
                    <li class="list-group-item"><h6 class="card-title">Description :</h6>
                        <p>{{ ad.description }}</p></li>
                </ul>


                <a href="{{ path('demand', {'id': ad.id}) }}" class="btn btn-success">Faire une demande</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une annonce{% endblock %}

{% block body %}
    <h1 class="text-center">Ajout d'une annonce</h1>
    <div class="d-flex justify-content-center mt-5">
        <div  class="col-6">
            {{ form_start(form) }}
            {{ form_row(form.title) }}
            {{ form_row(form.description) }}
            {{ form_row(form.dogs) }}

            {# On ajoute un bouton de validation du formulaire, nous n'en avons pas mis dans notre objet TagType #}
            <button type="submit" class="btn btn-primary">Valider</button>
            {# On affiche la balise </form> et les éventuels champs qui n'aurait pas été affichés jusqu'ici #}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}